apiVersion: apps/v1
kind: Deployment
metadata:
  name: author-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: author
  template:
    metadata:
      labels:
        app: author
    spec:
      containers:
        - name: author
          image: mehieddine/author
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ticketing            
            - name: MONGO_URI
              value: 'mongodb://author-mongo-srv:27017/author'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: author-srv
spec:
  selector:
    app: author
  ports:
    - name: author
      protocol: TCP
      port: 3000
      targetPort: 3000
